### ISSUE TITLE
No longer works on latest hyprland

### ISSUE THREAD

**Issue by Mr-Ples** [Euro20179/HyKeys#1]
installed hyprland-git 0.37.1.r64.35641463-1 from yay

hyprpm says hykeys is enabled 

listen to ipc sock, all events work fine but keys are no longer sent to ipc

**Comment by Euro20179** [comment]
I'm unable to reproduce this (with hyprland-git), idrk hyprland that well, so the best i can give you is try `hyprpm update`

**Comment by Mr-Ples** [comment]
that worked lol
